on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: make a comment
        if: github.event.pull_request.merged
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "@${{ github.event.pull_request.merged_by.login }}, good job!"
