on:
  pull_request:
    types: closed
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: cat $GITHUB_EVENT_PATH
      - name: second step
        run: printenv
