on:
  push:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          ref: refs/heads/master
      - run: ls -alFR $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE
      - run: git branch copy-dir-${GITHUB_SHA}
      - run: git checkout copy-dir-${GITHUB_SHA}
      - run: mkdir -p copy-github
      - run: cp -r .github/* copy-github
      # - id: check-diff
      #   run: |
      #     git diff --name-only | grep -E '^.github/'
      #     echo ::set-output name=exists::$?
      - id: check-diff
        run: |
          echo ::set-output name=exists::0
      - if: steps.check-diff.outputs.exists == '0'
        run: |
          git add .
          git config user.name "${GITHUB_ACTOR}"
          git commit -m "copy after ${GITHUB_SHA}"
          git push origin copy-dir-${GITHUB_SHA}
      - name: docker image ls
        run: docker image ls
      - name: show full event
        run: cat $GITHUB_EVENT_PATH
      - name: show system env
        run: printenv
      - uses: actions/hello-world-docker-action@b136eb8
        with:
          who-to-greet: 'Mona the Octocat'
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(context))
