on:
  push:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: show full event
        run: cat $GITHUB_EVENT_PATH
      - name: show system env
        run: printenv
      - name: output test secret
        run: echo ${{ secrets.TEST_SECRET }}
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload.repository.issues_url)
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(JSON.stringify(github))
      # - name: make a comment
      #   uses: actions/github-script@0.3.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       github.issues.createComment({
      #         owner: context.payload.repository.owner.name,
      #         repo: context.payload.repository.name,
      #         issue_number: not found in `context`
      #         body: `@${github.event.pull_request.merged_by.login}, nice work!`
      #       })
